import Head from 'next/head'
import HomePage from '@/components/layout/homePage'

const Home = () => {
  return (
    <>
      <Head>
        <title>CHOCH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HomePage />
    </>
  )
}

export default Home
