import Head from 'next/head'
import SingUp from '@/components/templates/AuthPage/SingUp'

function Auth() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <SingUp />
    </>
  )
}

export default Auth
